[book]
authors = ["Limp Cheney"]
language = "en"
multilingual = false
src = "src"
title = " limpbook"
description = "Some serious shit right here"

[build]
create-missing = false

[output.html]
smart-punctuation = true
mathjax-support = true
no-section-label = true
additional-css = ["theme/css/page-toc.css"]
additional-js = ["theme/page-toc.js"]
git-repository-url = "https://github.com/limpdev/LimpBook"
git-repository-icon = "fa-github"

[output.html.fold]
enable = true
level = 0

[output.html.search]
enable = false


[output.html.playground]
runnable = false
