[book]
authors = ["Limp Cheney"]
language = "en"
multilingual = false
src = "src"
title = "LimpBook"
description = "Documentation for all of my favourite tools!"

[output.html]
smart-punctuation = true
mathjax-support = true
no-section-label = true

[output.html.fold]
enable = true
level = 0
