[book]
authors = ["Limp Cheney"]
language = "en"
multilingual = false
src = "src"
title = " limpbook"
description = "Some serious shit right here"

[build]
create-missing = false

[output.html]
smart-punctuation = true
mathjax-support = false
no-section-label = true
additional-css = ["theme/css/page-toc.css"]
additional-js = ["theme/page-toc.js"]
git-repository-url = "https://github.com/limpdev/LimpBook"
git-repository-icon = "fa-github"

[output.html.fold]
enable = true
level = 0

[preprocessor.codeport]
command = "pre/mdbook-codeport/target/debug/mdbook-codeport.exe"

# [preprocessor.color-picker]
# command = "sed 's/:!pick:/{{color_picker_html}}/g'"

[output.html.search]
enable = false

[output.html.playground]
runnable = false
