[book]
authors = ["Limp Cheney"]
language = "en"
src = "src"
build-dir = "book"
title = "LimpBook"
description = "Some serious shit right here"

[build]
create-missing = false
extra-watch-dir = ["static"]

[output.html.fold]
enable = true
level = 0

[output]
[output.html]
additional-css = ["./pre/mdbook-admonish.css", "./theme/pagetoc.css", "theme/clipb.css"]
additional-js  = ["./RIPPLES.js", "./MARKTAG.js", "./theme/pagetoc.js", "theme/clipb.js"]
smart-punctuation = true
mathjax-support = false
no-section-label = true
git-repository-url = "https://github.com/limpdev/LimpBook"
git-repository-icon = "fa-github"
theme = "theme"
default-theme = "ayu"

[preprocessor]
[preprocessor.codeport]
command = "pre/codeport/codeport.exe"
[preprocessor.admonish]					# Callouts, a new kind of way
command = "mdbook-admonish"				# Uses code syntax:
assets_version = "3.0.3"				# 	```admonish
[preprocessor.alerts]					# Handles the GitHub flavored Callouts/Alerts
[preprocessor.embedify]					# Embed apps within the book - try YouTube!
[preprocessor.hide]						# Support for hidden chapters
hide = true								# Add "<!--hidden-->", at top of file

[output.html.search]
enable = false
